# 1. DEFINING WORKFLOWS
# 2. CORE COMPONENTS

name: Java CI/CD with Maven

# 3. EVENTS / TRIGGERS
# 4. WORKFLOW EXECUTION

on: # [required] GitHub event that triggers the workflow
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Specifying triggers

jobs: # [required] - Define at least one job with a sequence of steps
  build:
    # 5. RUNNERS
    runs-on: ubuntu-latest
    # 6. ACTIONS
    steps:
      # Select an action from actions/ where reusable code is hosted
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        # Run a command-line command
        run: mvn -B package
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target-files
          path: target
